@liferay_sample_etc_dot_net_HostAddress = http://localhost:5084

GET {{liferay_sample_etc_dot_net_HostAddress}}/weatherforecast/
Accept: application/json

GET {{liferay_sample_etc_dot_net_HostAddress}}/ready/
Accept: application/json

### POST {{liferay_sample_etc_dot_net_HostAddress}}/object/action/1
### Accept: application/json

###
